[project]
name = "logue"
version = "0.1.0"
description = "Logue App for Honda Prologue"
dependencies = [
    "flet",
    "requests",
    "paho-mqtt>=2.0.0",
    "python-dotenv",
    "cryptography",
]

[tool.flet]
product = "Logue"
